### PR TITLE
Load ESM plugins without touching filesystem

### PR DESCRIPTION
**Pull request by overlookmotel**
Load ESM plugin without touching filesystem. This is useful if the directory is read-only, and avoids unnecessary IO work.

You might feel it is not a good idea as it uses undocumented `Module.prototype._compile`.

Also includes the changes proposed in #20 and #21.

Sorry for the rash of PRs!

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Thanks for opening a PR! Can you please add a unit test?

**Comment by overlookmotel** [comment]
Thanks for quick response. Could certainly add tests for #20 and #21 (and those changes are included in this PR too).

A test for the main change in this PR - avoiding writing temp file to the filesystem - would be a bit cumbersome (patching `fs` maybe) and the test would seem a bit redundant once the filesystem interaction is removed entirely from the code. Is it necessary?

I'd be interested in whether you think this change is wise anyway.

It could be simplified further to remove calculating a fake file path. The fake file bypasses the CJS module cache entirely, so the path to that file is irrelevant and I don't think has to be unique.

```js
const Module = _require('module')
const module = new Module(name)
module._compile(
  `module.exports = import(${JSON.stringify(opts.path)})`,
  __filename // <-- irrelevant
)
plugin = module.exports
```

**Comment by mcollina** [comment]
You are right, a test is not needed for this one.

**Comment by mcollina** [comment]
I would still generate something that could look decent in a stack trace.

**Comment by overlookmotel** [comment]
How about `__filename` then? That'd be less mysterious to the user than `.esm-wrapper-44352-1.js`, especially when they can't find that file anywhere.

**Comment by mcollina** [comment]
`__filename` is not ok because it's the current file. If you are loading `plugin.js`, you might want to call the wrapper `esm-wrapper-plugin.js`.

**Comment by overlookmotel** [comment]
Yes, that was exactly my intention. What would appear in the stack trace is `/path/to/app/node_modules/fastify-sandbox/index.js`. That'd make it clear to user that the plugin was loaded by fastify-sandbox. Whereas `/path/to/app/esm-wrapper-plugin.js` is a file that doesn't exist and gives the user no clue as to where it came from - that seems more confusing.

**Comment by mcollina** [comment]
Then `/path/to/app/node_modules/fastify-sandbox/virtual-esm-wrapper.js` would do. It should be a file that does not exists otherwise it would be confusing for people finding a different content than what the error would tell.

**Comment by overlookmotel** [comment]
Changes made. `virtual-esm-wrapper.js` it is.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by overlookmotel** [comment]
Thanks very much for pushing this through so quickly.

**Pull request merged**
